name: e2e-test

run-name: Scaf End-to-End Tests

on: [push]

env:
  NODE_VERSION: 20

jobs:
  create-sample-project:
    name: Create sample project
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install npm package dependencies
        working-directory: packages/scaf
        run: npm install
      - name: Compile TS
        working-directory: packages/scaf
        run: npm run build
      - name: Initialise sample project
        working-directory: packages/scaf
        run: npm run scaf init
